apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: curri-service-users
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: curri-service-users
    spec:
      containers:
      - name: curri-service-users
        image: eu.gcr.io/iconic-setup-91510/curri-service-users:%VERSION%
        ports:
        - containerPort: 9000
        env:
        - name: SPRING_DATA_MONGODB_HOST
          value: mongo-users
        - name: SPRING_DATA_MONGODB_PORT
          value: 27017
