apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: curri-service-users
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: curri-service-users
    spec:
      containers:
      - name: curri-service-users
        image: %REGISTRY%/%APP_NAME%:%VERSION%
        ports:
        - containerPort: 9000
